name: Daily Job Monitor

on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC = 07:00 Stockholm (CET) / 08:00 CEST
  workflow_dispatch:      # Allow manual trigger from GitHub UI

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore seen_jobs database
        uses: actions/cache@v4
        with:
          path: seen_jobs.db
          key: seen-jobs-db-${{ github.run_id }}
          restore-keys: |
            seen-jobs-db-

      - name: Run job monitor
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python main.py

      - name: Save seen_jobs database
        uses: actions/cache@v4
        with:
          path: seen_jobs.db
          key: seen-jobs-db-${{ github.run_id }}
